

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_housing_development

test:
  <<: *default
  database: rails_housing_test

production:
  <<: *default
  database: rails_housing_production
  username:
  password:
